---
title: "Prueba de hipótesis para la diferencia de medias"
output: html_document
---

Suponga que se tienen dos muestras aleatorias que provienen de poblaciones normales así:

* $n_{1}$ observaciones $X_{11},\;X_{12},\;...\;X_{1,n_{1}}$ de una población I con media $\mu_{1}$ y varianza $\sigma_{1}^2$,
* $n_{2}$ observaciones $X_{21},\;X_{22},\;...\;X_{2,n_{2}}$ de una población II con media $\mu_{2}$ y varianza $\sigma_{2}^2$,
* ambas muestras son independientes entre sí.

En este problema se quiere estudiar la hipótesis nula $H_{0}:\mu_{1}-\mu_{2}=\delta_{0}$ y se sospecha que la diferencia de medias $\mu_{1}-\mu_{2}$ podría estar en alguna de las siguientes situciones:

* $H_{a}: \mu_{1}-\mu_{2}<\delta_{0}$
* $H_{a}: \mu_{1}-\mu_{2}\neq\delta_{0}$
* $H_{a}: \mu_{1}-\mu_{2}>\delta_{0}$

El valor $\delta_{0}$ corresponde a la diferencia entre las medias poblacionales; cuando $\delta_{0}=0$, la hipótesis nula se convierte en $H_{0}: \mu_{1}=\;\mu_{2}$ lo que significa que se está probando igualdad de medias.

Para realizar esta prueba de hipótesis se deben diferenciar dos casos, uno en el que las varianzas poblacionales son iguales y otro en el que las varianzas poblacionales son diferentes, esto se puede chequear utilizando la prueba de comparación de varianzas. Para cada uno de los casos hay un estadístico de prueba, una distribución asociada y un valor-$P$, a continuación se presentan los dos casos en detalle.


##Caso 1: varianzas poblacionales iguales $\sigma_{1}^2=\sigma_{2}^2$

En este caso el estadístico para realizar la prueba es:

$$T_{0}=\dfrac{\overline{X}_{1}-\overline{X}_{2}-\delta_{0}}{S_{p}\sqrt{\dfrac{1}{n_{1}}+\dfrac{1}{n_{2}}}},$$
donde $\overline{X}_{1}$ y $\overline{X}_{2}$ son las medias de las muestras I y II respectivamente; la cantidad $S_{p}^2$ es una varianza combinada y se calcula como:

$$S_{p}^2=\dfrac{(n_{1}-1)S_{1}^2+(n_{2}-1)S_{2}^2}{n_{1}+n_{2}-2},$$
donde $S_{1}^2$ y $S_{2}^2$ son las varianzas de las muestras I y II respectivamente. En este caso el estadístico $T_{0}$, bajo suposición que $H_{0}$ es verdadera, tiene distribución $t$-student con $n_{1}+n{2}-2$ grados de libertad.

Si el valor calculado para el estadístico dado la ecuación se denota por $t_{0}$, entonces el valor-$P$ de la prueba se calcula de acuerdo a la hipótesis alterna $H_{a}$ así:

* Si $H_{a}:\mu_{1}-\mu_{2}<\delta_{0}$ entonces valor-$P$ = P$(t_{n_{1}+n_{2}-2}<t_{0}).$
* Si $H_{a}:\mu_{1}-\mu_{2}\neq\delta_{0}$ entonces valor-$P$ = 2 x P$(t_{n_{1}+n_{2}-2}> |t_{0}|).$
* Si $H_{a}:\mu_{1}-\mu_{2}>\delta_{0}$ entonces valor-$P$ = P$(t_{n_{1}+n_{2}-2}>t_{0}).$

##Caso 2: varianzas poblacionales diferentes $\sigma_{1}^2\neq\sigma_{2}^2$

En este caso el estadístico para realizar la prueba es

$$$$

Bajo la suposición de que $H_{0}$ es verdadera, $T_{0}$ tiene distribución $t$-student con $\nu$ grados de libertad, en donde $\nu$ se calcula como:

$$\nu=\dfrac{\left(\dfrac{S_{1}^2}{n_{1}}+\dfrac{S_{2}^2}{n_{2}}\right)^2}{\dfrac{(S_{1}^2/n_{1})^2}{n_{1}-1}+\dfrac{(S_{2}^2/n_{2})^2}{n_{2}-1}}$$
Si el valor calculado para el estadístico dado en la ecuación se denota por $t_{0}$, entonces el valor-$P$ de la prueba se calcula de acuerdo a la hipótesis alterna $H_{a}$ así:

* Si $H_{a}:\mu_{1}-\mu_{2}<\delta_{0}$ entonces valor-$P$ = P$(t_{\nu}<t_{0}).$
* Si $H_{a}:\mu_{1}-\mu_{2}\neq\delta_{0}$ entonces valor-$P$ = 2 x P$(t_{\nu}>|t_{0}|).$
* Si $H_{a}:\mu_{1}-\mu_{2}>\delta_{0}$ entonces valor-$P$ = P$(t_{\nu}>t_{0}).$