---
title: "Prueba de hipótesis para la media "
output: html_document
---
Suponga que se tiene una muestra aleatoria $X_{1}, \;X_{2},..., \;X_{n}$ proveniente de una población normal. Se quiere estudiar la hipótesis nula $H_{0} : \mu = \mu_{0}$ y se sospecha que la media $\mu$ cumple una de las siguientes situaciones:


1. $H_{a} \;: \mu \ < \mu_{0}$
2. $H_{a} \;: \mu \ \neq \mu_{0}$
3. $H_{a} \;: \mu \ > \mu_{0}$


El estadístico para realizar la prueba es

$$T_{0} = \dfrac{\overline{X} - \mu_{0}}{S/\sqrt{n}},$$
donde $\overline{X}\; \;y \; \;S$ son la media y desviación estándar muestral respectivamente.

Bajo la suposición de que $H_{0}$ es verdadera, $T_{0}$ tiene distribución $t-$student con $n\;-\;1$ grados de libertad.

Si el valor calculado para el estadístico dado en la ecuación anterior se denota por $t_{0}$, entonces el valor-$P$ de la prueba se calcula de acuerdo a la hipótesis alterna $H_{a}$ así:


* Si $H_{a} \;: \mu \ < \mu_{0}$ entonces valor-$P$= $P(t_{n-1} \;<\;t_{0})$  
* Si $H_{a} \;: \mu \ \neq \mu_{0}$ entonces valor-$P$= $P(t_{n-1} \;>\;|t_{0}|)$  
* Si $H_{a} \;: \mu \ > \mu_{0}$ entonces valor-$P$= $P(t_{n-1} \;>\;t_{0})$  
 
Si se dá el caso en que la muestra aleatoria no proviene de una población normal pero se cumple que $n\geq 40$, entonces el estadístico para realizar la prueba es:

$$Z_{0} = \dfrac{\overline{X}-\mu_{0}}{S/\sqrt{n}}$$
y en este caso el estadístico $Z_{0}$, en virtud del Teorema del Límite Central, tiene una distribución $Z\;\sim\;N(0,1)$ bajo la suposición de que  $H_{0}$ es verdadera. Si el valor calculado del estadístico es  $Z_{0}$, se pueden usar las expresiones anteriores para calcular el valor-$P$ sustituyendo $t_{0}$ por $z_{0}$ y $t_{n-1}$ por $z$.

En cualquiera de los casos, la hipótesis nula $H_{0}$ se rechaza si el valor-$P$ es menor que el nivel de significancia $(\alpha)$ fijado previamente por el analista.

